src/books/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
    livro,
    criarLivro,
    alteraLivro,
    deletaLivro
    )

urlpatterns = [
    url(r'^$', livro, name='livro_lista'),
    url(r'^criar/$', criarLivro, name="livro_criar"),
    url(r'^(?P<pk>\d+)/alterar/$', alteraLivro, name='livro_alterar'),
    url(r'^(?P<pk>\d+)/deletar/$', deletaLivro, name='livro_deletar'),
]

src/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns

from django.conf.urls import url, include # Incluir outras URLs

from src.books import urls # Multiplas URLS a fim de manter a URL principal mais clean

urlpatterns = i18n_patterns (
    url(r'^admin/', admin.site.urls),
    url(r'^livros/', include('src.books.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
)

src/books/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


from .data import tiposLivro
# Create your models here.
class Livro(models.Model):
    titulo         = models.CharField('Título', max_length=50)
    dataPublicacao = models.DateField('Data de Publicação', null=True)
    autor          = models.CharField('Autor', max_length=30, blank=True)
    preco          = models.DecimalField('Preço', max_digits=5, decimal_places=2)
    paginas        = models.IntegerField('Qntd. de Páginas', blank=True, null=True)
    tipoLivro      = models.PositiveSmallIntegerField('Tipo de Livro', choices=tiposLivro)

    class Meta:
        ordering = ['titulo']
        verbose_name = "livro"
        verbose_name_plural = "livros"

    def __str__(self):
        return self.titulo + ' - ' + self.autor

src/core/models.py
from django.db import models

# Create your models here.

src/books/forms.py
from django import forms
from .models import Livro

class LivroForm(forms.ModelForm):
    class Meta:
        model  = Livro
        fields =  ('titulo', 'dataPublicacao', 'autor', 'preco', 'paginas', 'tipoLivro', )  

src/books/views.py
from django.shortcuts import render, get_object_or_404

from django.http import JsonResponse
from django.template.loader import render_to_string

from .models import Livro
from .forms import LivroForm

def livro(request):
    livros = Livro.objects.all().order_by('-id')
    return render(request, 'livros.html', {'livros': livros})

def salvar_form_livro(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            livros = Livro.objects.all().order_by('-id')
            data['html_book_list'] = render_to_string('listaLivros.html', {
                'livros': livros
            })
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)

def criarLivro(request):
    if request.method == 'POST':
        form = LivroForm(request.POST)
    else:
        form = LivroForm()
    return salvar_form_livro(request, form, 'cadastraLivro.html')

def alteraLivro(request, pk):
    livro = get_object_or_404(Livro, pk=pk)
    if request.method == 'POST':
        form = LivroForm(request.POST, instance=livro)
    else:
        form = LivroForm(instance=livro)
    return salvar_form_livro(request, form, 'alteraLivro.html')

def deletaLivro(request, pk):
    livro = get_object_or_404(Livro, pk=pk)
    data = dict()
    if request.method == 'POST':
        livro.delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        livros = Livro.objects.all()
        data['html_book_list'] = render_to_string('listaLivros.html', {
            'livros': livros
        })
    else:
        context = {'livro': livro}
        data['html_form'] = render_to_string('deletaLivro.html',
            context,
            request=request,
        )
    return JsonResponse(data)

src/core/views.py
from django.shortcuts import render

# Create your views here.

src/core/templates/alteraLivro.html
<form method="post" action="{% url 'livro_alterar' form.instance.pk %}" class="js-book-update-form">
    {% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Alterar Livro</h4>
    </div>
    <div class="modal-body">
        {% include 'form.html' %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Update book</button>
    </div>
</form>

src/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Manter Livros</title>
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    </head>
    <body>

        {% include "navbar.html" %}

        <div class="container">
            {% block content %}
            {% endblock %}
        </div>

        <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>  <!-- JQUERY HERE -->
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        {% block javascript %}
        {% endblock %}
    </body>
</html>

src/core/templates/cadastraLivro.html
<form method="post" action="{% url 'livro_criar' %}" class="js-book-create-form">
	{% csrf_token %}
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		<h4 class="modal-title">Criar um novo livro</h4>
	</div>
	<div class="modal-body">
		{% include "form.html" %}
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
		<button type="submit" class="btn btn-primary">Criar livro</button>
	</div>
</form>

src/core/templates/deletaLivro.html
<form method="post" action="{% url 'livro_deletar' livro.id %}" class="js-book-delete-form">
    {% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Confirmar exclusão do livro</h4>
    </div>
    <div class="modal-body">
        <p class="lead">Você tem certeza de que deseja deletar o livro: <strong>{{ livro.titulo }}</strong>?</p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="submit" class="btn btn-danger">Deletar Livro</button>
    </div>
</form>

src/core/templates/form.html
{% load widget_tweaks %}

{% for field in form %}
    <div class="form-group {% if field.errors %} has-error {% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
        {% endfor %}
    </div>
{% endfor %}

<!-- Dont Repeat Yourself, como iria usar esse trecho em dois locais deixei em um só -->

src/core/templates/listaLivros.html
{% for livro in livros %} <!-- for nomeFuncao in nomeVariavel que recebe os dados -->
    <tr>
        <td>{{ livro.id }}</td>
        <td>{{ livro.titulo }}</td>
        <td>{{ livro.autor }}</td>
        <td>{{ livro.get_tipoLivro_display }}</td>
        <td>{{ livro.dataPublicacao }}</td>
        <td>{{ livro.paginas }}</td>
        <td>{{ livro.preco }}</td>
        <td>
            <button type="button"
                    class="btn btn-warning btn-sm js-update-book"
                    data-url="{% url 'livro_alterar' livro.id %}">
                    <span class="glyphicon glyphicon-pencil"></span> Alterar
            </button>
            <button type="button"
                    class="btn btn-danger btn-sm js-delete-book"
                    data-url="{% url 'livro_deletar' livro.id %}">
                    <span class="glyphicon glyphicon-trash"></span> Deletar
            </button>
        </td>
    </tr>
{% empty %}
    <tr>
        <td colspan="7" class="text-center bg-warning">Não há livros cadastrados</td>
    </tr>
{% endfor %}

src/core/templates/livros.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block javascript %}
    <script src="{% static "js/livros.js" %}"></script>
{% endblock %}

{% block content %}


    <div id="languages">
        <table >
            <tr>
                {% get_available_languages as languages %}
                {% for key, item in languages %}
                    <td>
                        <form action="{% url 'set_language' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="language" value="{{key}}"/>
                            <input id="lang_select_{{key}}" type = "image" src="/media/img/{{ key }}.gif" alt="{{ item }}"/>
                        </form>
                    </td>
                {% endfor %}
            </tr>
        </table>
    </div>


    <h1 class="page-header">{% trans 'Livros' %}</h1>

    <p>
        <button type="button"
                class="btn btn-primary js-create-book"
                data-url="{% url 'livro_criar' %}">
                <span class="glyphicon glyphicon-plus"></span>
                {% trans 'Novo Livro' %}
        </button>
    </p>

    <table class="table" id="book-table">
        <thead>
            <tr>
                <th>#</th>
                <th>{% trans 'Título' %}</th>
                <th>{% trans 'Autor' %}</th>
                <th>{% trans 'Tipo' %}</th>
                <th>{% trans 'Data de Publicação' %}</th>
                <th>{% trans 'Quantidade Páginas' %}</th>
                <th>{% trans 'Preço' %}</th>
            </tr>
        </thead>
        <tbody>
            {% include "listaLivros.html" %}
        </tbody>
    </table>


    <div class="modal fade" id="modal-book">
        <div class="modal-dialog">
            <div class="modal-content">
            </div>
        </div>
    </div>

{% endblock %}

src/core/templates/navbar.html
<nav class="navbar navbar-default">
	<div class="container">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">Livraria</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li class="active"><a href="#">Livros <span class="sr-only">(current)</span></a></li>
			</ul>

		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>